### PR TITLE
Add the ability to add a listener that will receive audio focus changes

### PR DESCRIPTION
**Pull request by agnusin**
## Description

Add the ability to add a listener that will receive audio focus changes

## Breakdown

- [Bulleted summary of changes]
- [eg. Add new public function to `Authenticator.kt` ]
- [eg. Add new string resources to `strings.xml`]

## Validation

- [Bulleted summary of validation steps]
- [eg. Add new unit tests to validate changes]
- [eg. Verified all CI checks pass on the feature branch]

## Additional Notes

[Any additional comments, notes, or information relevant to reviewers.]

## Submission Checklist
 - [x] The source has been evaluated for semantic versioning changes and are reflected in `gradle.properties`
 - [x] The `CHANGELOG.md` reflects any **feature**, **bug fixes**, or **known issues** made in the source code

### CODE REVIEW

**Comment by agnusin** [comment]
@Alton09 thank you for your comments ! I've fixed that.

**Comment by agnusin** [comment]
@Alton09 @aaalaniz what else should I do to get my changes into 3.0?

**Comment by agnusin** [comment]
@Alton09 @aaalaniz what else should I do to get my changes into next release?

**Comment by aaalaniz** [comment]
Hey @agnusin 

The changes are good! @Alton09 is working on a PR from a branch on the main repository so that we can run these changes through the CI pipeline where unit and integration tests can be run. I will close this PR for now and @Alton09 will submit a PR shortly with your changes and reference this original work.

We recently put together a short [contributing guide](https://github.com/twilio/audioswitch#contributing). With respect to next steps, can you submit a separate PR that adds you to the [CONTRIBUTORS](https://github.com/twilio/audioswitch/blob/master/CONTRIBUTORS.md) file? Since @Alton09 will merge your changes from his own PR you will not show up on the contributors page without this. 

Thank you for your contribution!

**Pull request closed without merging**
